const SELECT_ARCH = 'SELECT_ARCH';
const SELECT_CHANNEL = 'SELECT_CHANNEL';
const SELECT_SERIES = 'SELECT_SERIES';
const SELECT_QUERY = 'SELECT_QUERY';
const INVALIDATE_QUERY = 'INVALIDATE_QUERY';
const REQUEST_SNAPS = 'REQUEST_SNAPS';
const RECEIVE_SNAPS = 'RECEIVE_SNAPS';

export {
  INVALIDATE_QUERY,
  SELECT_ARCH,
  SELECT_CHANNEL,
  SELECT_SERIES,
  SELECT_QUERY,
  RECEIVE_SNAPS,
  REQUEST_SNAPS
}
