const SELECT_ARCH = 'SELECT_ARCH';
const SELECT_CHANNEL = 'SELECT_CHANNEL';
const SELECT_SERIES = 'SELECT_SERIES';
const SELECT_QUERY = 'SELECT_QUERY';
const SELECT_SNAP_ID = 'SELECT_SNAP_ID';
const REQUEST_QUERY_SNAPS = 'REQUEST_QUERY_SNAPS';
const RECEIVE_QUERY_SNAPS = 'RECEIVE_QUERY_SNAPS';
const REQUEST_SNAP = 'REQUEST_SNAP';
const RECEIVE_SNAP = 'RECEIVE_SNAP';

export {
  SELECT_ARCH,
  SELECT_CHANNEL,
  SELECT_SERIES,
  SELECT_QUERY,
  SELECT_SNAP_ID,
  REQUEST_QUERY_SNAPS,
  RECEIVE_QUERY_SNAPS,
  REQUEST_SNAP,
  RECEIVE_SNAP
}
