const IS_FUZZY = 'IS_FUZZY';
const RECEIVE_QUERY_SNAPS = 'RECEIVE_QUERY_SNAPS';
const RECEIVE_SNAP = 'RECEIVE_SNAP';
const REQUEST_QUERY_SNAPS = 'REQUEST_QUERY_SNAPS';
const REQUEST_SNAP = 'REQUEST_SNAP';
const SELECT_ARCH = 'SELECT_ARCH';
const SELECT_CHANNEL = 'SELECT_CHANNEL';
const SELECT_CONFINEMENT = 'SELECT_CONFINEMENT';
const SELECT_QUERY = 'SELECT_QUERY';
const SELECT_SERIES = 'SELECT_SERIES';
const SELECT_SNAP_ID = 'SELECT_SNAP_ID';

export {
  IS_FUZZY,
  RECEIVE_QUERY_SNAPS,
  RECEIVE_SNAP,
  REQUEST_QUERY_SNAPS,
  REQUEST_SNAP,
  SELECT_ARCH,
  SELECT_CHANNEL,
  SELECT_CONFINEMENT,
  SELECT_QUERY,
  SELECT_SERIES,
  SELECT_SNAP_ID,
};
